---
name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout and setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install .
          python3 -c "import paccmann"
          training_paccmann -h
